version: 2

builds:
  - id: setup
    binary: setup
    main: ./cmd/setup
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.buildDate={{ .Date }}

archives:
  - formats: ['binary']
